# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(991, 574)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 241, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 241, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 241, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 241, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 241, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(248, 248, 248))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(161, 161, 161))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 241, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 241, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(241, 241, 241))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        MainWindow.setPalette(palette)
        MainWindow.setAutoFillBackground(True)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralWidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 931, 481))
        self.tabWidget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.tabWidget.setToolTip("")
        self.tabWidget.setAutoFillBackground(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_12 = QtWidgets.QLabel(self.tab)
        self.label_12.setGeometry(QtCore.QRect(170, 20, 561, 341))
        self.label_12.setAutoFillBackground(True)
        self.label_12.setText("")
        self.label_12.setPixmap(QtGui.QPixmap("原理样机图.png"))
        self.label_12.setScaledContents(True)
        self.label_12.setObjectName("label_12")
        self.horizontalLayoutWidget_6 = QtWidgets.QWidget(self.tab)
        self.horizontalLayoutWidget_6.setGeometry(QtCore.QRect(90, 390, 711, 51))
        self.horizontalLayoutWidget_6.setObjectName("horizontalLayoutWidget_6")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_6.setSpacing(6)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_13 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_6.addWidget(self.label_13)
        self.lineEdit_UserName = QtWidgets.QLineEdit(self.horizontalLayoutWidget_6)
        self.lineEdit_UserName.setObjectName("lineEdit_UserName")
        self.horizontalLayout_6.addWidget(self.lineEdit_UserName)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.label_14 = QtWidgets.QLabel(self.horizontalLayoutWidget_6)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_6.addWidget(self.label_14)
        self.lineEdit_PassWord = QtWidgets.QLineEdit(self.horizontalLayoutWidget_6)
        self.lineEdit_PassWord.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.lineEdit_PassWord.setObjectName("lineEdit_PassWord")
        self.horizontalLayout_6.addWidget(self.lineEdit_PassWord)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.btn_Login = QtWidgets.QPushButton(self.horizontalLayoutWidget_6)
        self.btn_Login.setObjectName("btn_Login")
        self.horizontalLayout_6.addWidget(self.btn_Login)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_3.setGeometry(QtCore.QRect(0, 30, 901, 431))
        self.tabWidget_3.setAutoFillBackground(True)
        self.tabWidget_3.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget_3.setIconSize(QtCore.QSize(64, 16))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.formLayoutWidget = QtWidgets.QWidget(self.tab_9)
        self.formLayoutWidget.setGeometry(QtCore.QRect(260, 50, 351, 311))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.formLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 6, 0, 1, 1)
        self.comboBox_ScanMode = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_ScanMode.setObjectName("comboBox_ScanMode")
        self.comboBox_ScanMode.addItem("")
        self.comboBox_ScanMode.addItem("")
        self.comboBox_ScanMode.addItem("")
        self.gridLayout.addWidget(self.comboBox_ScanMode, 6, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 3, 0, 1, 1)
        self.lineEdit_ScanH = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_ScanH.setObjectName("lineEdit_ScanH")
        self.gridLayout.addWidget(self.lineEdit_ScanH, 4, 1, 1, 1)
        self.lineEdit_ScanN = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_ScanN.setObjectName("lineEdit_ScanN")
        self.gridLayout.addWidget(self.lineEdit_ScanN, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.lineEdit_ScanP = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_ScanP.setObjectName("lineEdit_ScanP")
        self.gridLayout.addWidget(self.lineEdit_ScanP, 0, 1, 1, 1)
        self.lineEdit_ScanK = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_ScanK.setObjectName("lineEdit_ScanK")
        self.gridLayout.addWidget(self.lineEdit_ScanK, 1, 1, 1, 1)
        self.lineEdit_ScanL = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_ScanL.setObjectName("lineEdit_ScanL")
        self.gridLayout.addWidget(self.lineEdit_ScanL, 2, 1, 1, 1)
        self.btn_WriteParameter = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_WriteParameter.setObjectName("btn_WriteParameter")
        self.gridLayout.addWidget(self.btn_WriteParameter, 5, 0, 1, 2)
        self.btn_ScanStart = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_ScanStart.setObjectName("btn_ScanStart")
        self.gridLayout.addWidget(self.btn_ScanStart, 7, 0, 1, 1)
        self.btn_ScanStop = QtWidgets.QPushButton(self.formLayoutWidget)
        self.btn_ScanStop.setObjectName("btn_ScanStop")
        self.gridLayout.addWidget(self.btn_ScanStop, 7, 1, 1, 1)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("tab_扫描控制.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_3.addTab(self.tab_9, icon, "")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.textEdit_4 = QtWidgets.QTextEdit(self.tab_10)
        self.textEdit_4.setGeometry(QtCore.QRect(190, 70, 361, 261))
        self.textEdit_4.setObjectName("textEdit_4")
        self.label_4 = QtWidgets.QLabel(self.tab_10)
        self.label_4.setGeometry(QtCore.QRect(190, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_4.setGeometry(QtCore.QRect(200, 350, 75, 23))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_3.setGeometry(QtCore.QRect(470, 350, 75, 23))
        self.pushButton_3.setObjectName("pushButton_3")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("tab_传感器校正.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_3.addTab(self.tab_10, icon1, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.graphicsView = QtWidgets.QGraphicsView(self.tab_3)
        self.graphicsView.setGeometry(QtCore.QRect(70, 70, 431, 321))
        self.graphicsView.setObjectName("graphicsView")
        self.textBrowser = QtWidgets.QTextBrowser(self.tab_3)
        self.textBrowser.setGeometry(QtCore.QRect(580, 70, 291, 321))
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(70, 30, 571, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_4.setContentsMargins(0, 11, 11, 11)
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.horizontalLayoutWidget_5 = QtWidgets.QWidget(self.tab_3)
        self.horizontalLayoutWidget_5.setGeometry(QtCore.QRect(70, 400, 591, 31))
        self.horizontalLayoutWidget_5.setObjectName("horizontalLayoutWidget_5")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_5.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_5 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_5.addWidget(self.pushButton_5)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.pushButton_6 = QtWidgets.QPushButton(self.horizontalLayoutWidget_5)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_5.addWidget(self.pushButton_6)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab_4)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 30, 931, 431))
        self.tabWidget_2.setAutoFillBackground(True)
        self.tabWidget_2.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget_2.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget_2.setIconSize(QtCore.QSize(64, 16))
        self.tabWidget_2.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_3.setGeometry(QtCore.QRect(100, 30, 231, 351))
        self.groupBox_3.setObjectName("groupBox_3")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_4.setGeometry(QtCore.QRect(410, 30, 411, 131))
        self.groupBox_4.setObjectName("groupBox_4")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab_8)
        self.groupBox_5.setGeometry(QtCore.QRect(410, 200, 411, 181))
        self.groupBox_5.setObjectName("groupBox_5")
        self.layoutWidget = QtWidgets.QWidget(self.tab_8)
        self.layoutWidget.setGeometry(QtCore.QRect(120, 40, 201, 331))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_21 = QtWidgets.QLabel(self.layoutWidget)
        self.label_21.setObjectName("label_21")
        self.verticalLayout.addWidget(self.label_21)
        self.comboBox_3 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.verticalLayout.addWidget(self.comboBox_3)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget)
        self.label_22.setObjectName("label_22")
        self.verticalLayout.addWidget(self.label_22)
        self.comboBox_4 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.verticalLayout.addWidget(self.comboBox_4)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget)
        self.label_23.setObjectName("label_23")
        self.verticalLayout.addWidget(self.label_23)
        self.comboBox_5 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.verticalLayout.addWidget(self.comboBox_5)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget)
        self.label_24.setObjectName("label_24")
        self.verticalLayout.addWidget(self.label_24)
        self.comboBox_6 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.verticalLayout.addWidget(self.comboBox_6)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget)
        self.label_25.setObjectName("label_25")
        self.verticalLayout.addWidget(self.label_25)
        self.comboBox_7 = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_7.setObjectName("comboBox_7")
        self.comboBox_7.addItem("")
        self.verticalLayout.addWidget(self.comboBox_7)
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_8)
        self.layoutWidget_2.setGeometry(QtCore.QRect(420, 40, 391, 101))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.gridLayout_3.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_3.addWidget(self.lineEdit_12, 1, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 1, 0, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 0, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.layoutWidget_2)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_3.addWidget(self.lineEdit_11, 0, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 1, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 0, 2, 1, 1)
        self.layoutWidget_3 = QtWidgets.QWidget(self.tab_8)
        self.layoutWidget_3.setGeometry(QtCore.QRect(420, 230, 391, 141))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_4.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_4.setSpacing(6)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_20 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_20.setObjectName("pushButton_20")
        self.gridLayout_4.addWidget(self.pushButton_20, 0, 0, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_4.addWidget(self.pushButton_2, 0, 1, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_4.addWidget(self.pushButton_18, 0, 2, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_4.addWidget(self.pushButton_19, 1, 0, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout_4.addWidget(self.pushButton_21, 1, 1, 1, 1)
        self.pushButton_22 = QtWidgets.QPushButton(self.layoutWidget_3)
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_4.addWidget(self.pushButton_22, 1, 2, 1, 1)
        self.layoutWidget_2.raise_()
        self.layoutWidget_3.raise_()
        self.layoutWidget.raise_()
        self.groupBox_3.raise_()
        self.groupBox_4.raise_()
        self.groupBox_5.raise_()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("未标题-1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tab_8, icon2, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.line = QtWidgets.QFrame(self.tab_11)
        self.line.setGeometry(QtCore.QRect(20, 10, 20, 401))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab_11)
        self.groupBox_6.setGeometry(QtCore.QRect(330, 140, 451, 171))
        self.groupBox_6.setFlat(False)
        self.groupBox_6.setCheckable(False)
        self.groupBox_6.setObjectName("groupBox_6")
        self.btn_SampleOff = QtWidgets.QPushButton(self.groupBox_6)
        self.btn_SampleOff.setGeometry(QtCore.QRect(30, 110, 75, 23))
        self.btn_SampleOff.setObjectName("btn_SampleOff")
        self.btn_SampleStop = QtWidgets.QPushButton(self.groupBox_6)
        self.btn_SampleStop.setGeometry(QtCore.QRect(180, 110, 75, 23))
        self.btn_SampleStop.setObjectName("btn_SampleStop")
        self.btn_SampleOriginStart = QtWidgets.QPushButton(self.groupBox_6)
        self.btn_SampleOriginStart.setGeometry(QtCore.QRect(180, 50, 75, 23))
        self.btn_SampleOriginStart.setObjectName("btn_SampleOriginStart")
        self.btn_SampleOn = QtWidgets.QPushButton(self.groupBox_6)
        self.btn_SampleOn.setGeometry(QtCore.QRect(30, 50, 75, 23))
        self.btn_SampleOn.setObjectName("btn_SampleOn")
        self.btn_SampleDirectionStart = QtWidgets.QPushButton(self.groupBox_6)
        self.btn_SampleDirectionStart.setGeometry(QtCore.QRect(320, 50, 75, 23))
        self.btn_SampleDirectionStart.setObjectName("btn_SampleDirectionStart")
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab_11)
        self.groupBox_7.setGeometry(QtCore.QRect(50, 50, 251, 261))
        self.groupBox_7.setObjectName("groupBox_7")
        self.label_32 = QtWidgets.QLabel(self.groupBox_7)
        self.label_32.setGeometry(QtCore.QRect(0, 20, 54, 12))
        self.label_32.setObjectName("label_32")
        self.label_31 = QtWidgets.QLabel(self.groupBox_7)
        self.label_31.setGeometry(QtCore.QRect(200, 200, 31, 16))
        self.label_31.setObjectName("label_31")
        self.label_33 = QtWidgets.QLabel(self.groupBox_7)
        self.label_33.setGeometry(QtCore.QRect(0, 130, 54, 12))
        self.label_33.setObjectName("label_33")
        self.label_30 = QtWidgets.QLabel(self.groupBox_7)
        self.label_30.setGeometry(QtCore.QRect(0, 180, 54, 12))
        self.label_30.setObjectName("label_30")
        self.comboBox_SampleMode = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_SampleMode.setGeometry(QtCore.QRect(0, 40, 191, 22))
        self.comboBox_SampleMode.setObjectName("comboBox_SampleMode")
        self.comboBox_SampleMode.addItem("")
        self.comboBox_SampleMode.addItem("")
        self.comboBox_SampleDirection = QtWidgets.QComboBox(self.groupBox_7)
        self.comboBox_SampleDirection.setGeometry(QtCore.QRect(0, 90, 191, 22))
        self.comboBox_SampleDirection.setObjectName("comboBox_SampleDirection")
        self.comboBox_SampleDirection.addItem("")
        self.comboBox_SampleDirection.addItem("")
        self.label_35 = QtWidgets.QLabel(self.groupBox_7)
        self.label_35.setGeometry(QtCore.QRect(0, 70, 54, 12))
        self.label_35.setObjectName("label_35")
        self.lineEdit_SampleDestPosition = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_SampleDestPosition.setGeometry(QtCore.QRect(0, 150, 191, 20))
        self.lineEdit_SampleDestPosition.setObjectName("lineEdit_SampleDestPosition")
        self.lineEdit_SampleSpeed = QtWidgets.QLineEdit(self.groupBox_7)
        self.lineEdit_SampleSpeed.setGeometry(QtCore.QRect(0, 200, 191, 20))
        self.lineEdit_SampleSpeed.setObjectName("lineEdit_SampleSpeed")
        self.label_34 = QtWidgets.QLabel(self.groupBox_7)
        self.label_34.setGeometry(QtCore.QRect(200, 150, 21, 16))
        self.label_34.setObjectName("label_34")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab_11)
        self.groupBox_8.setGeometry(QtCore.QRect(330, 50, 211, 80))
        self.groupBox_8.setObjectName("groupBox_8")
        self.comboBox_SampleSelect = QtWidgets.QComboBox(self.groupBox_8)
        self.comboBox_SampleSelect.setGeometry(QtCore.QRect(60, 30, 91, 21))
        self.comboBox_SampleSelect.setEditable(False)
        self.comboBox_SampleSelect.setObjectName("comboBox_SampleSelect")
        self.comboBox_SampleSelect.addItem("")
        self.comboBox_SampleSelect.addItem("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("样品台控制器.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tab_11, icon3, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_12)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(120, 20, 321, 331))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(11, 11, 11, 11)
        self.gridLayout_2.setSpacing(6)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem4, 0, 3, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 2, 3, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 3, 3, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem7, 1, 3, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 0, 4, 1, 1)
        self.btn_XrayStart = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_XrayStart.setObjectName("btn_XrayStart")
        self.gridLayout_2.addWidget(self.btn_XrayStart, 0, 5, 1, 1)
        self.lineEdit_XrayKv = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_XrayKv.setObjectName("lineEdit_XrayKv")
        self.gridLayout_2.addWidget(self.lineEdit_XrayKv, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_16.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 0, 0, 1, 1)
        self.btn_XrayExpose = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_XrayExpose.setObjectName("btn_XrayExpose")
        self.gridLayout_2.addWidget(self.btn_XrayExpose, 2, 5, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 3, 4, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 3, 0, 1, 1)
        self.btn_XrayStop = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_XrayStop.setObjectName("btn_XrayStop")
        self.gridLayout_2.addWidget(self.btn_XrayStop, 3, 5, 1, 1)
        self.lineEdit_XrayMa = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_XrayMa.setObjectName("lineEdit_XrayMa")
        self.gridLayout_2.addWidget(self.lineEdit_XrayMa, 1, 1, 1, 1)
        self.lineEdit_XrayTime = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_XrayTime.setObjectName("lineEdit_XrayTime")
        self.gridLayout_2.addWidget(self.lineEdit_XrayTime, 2, 1, 1, 1)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem10, 1, 4, 1, 1)
        self.btn_XrayPrepare = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btn_XrayPrepare.setObjectName("btn_XrayPrepare")
        self.gridLayout_2.addWidget(self.btn_XrayPrepare, 1, 5, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 2, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem11, 2, 4, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 1, 0, 1, 1)
        self.comboBox_XrayFcoal = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_XrayFcoal.setObjectName("comboBox_XrayFcoal")
        self.comboBox_XrayFcoal.addItem("")
        self.comboBox_XrayFcoal.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_XrayFcoal, 3, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem12, 1, 2, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem13, 0, 2, 1, 1)
        self.label_XrayStatus = QtWidgets.QLabel(self.tab_12)
        self.label_XrayStatus.setGeometry(QtCore.QRect(0, 400, 61, 21))
        self.label_XrayStatus.setObjectName("label_XrayStatus")
        self.textEdit_XrayLog = QtWidgets.QTextEdit(self.tab_12)
        self.textEdit_XrayLog.setGeometry(QtCore.QRect(560, 70, 231, 231))
        self.textEdit_XrayLog.setObjectName("textEdit_XrayLog")
        self.groupBox = QtWidgets.QGroupBox(self.tab_12)
        self.groupBox.setGeometry(QtCore.QRect(110, 40, 351, 281))
        self.groupBox.setObjectName("groupBox")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_12)
        self.groupBox_2.setGeometry(QtCore.QRect(540, 40, 281, 281))
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.gridLayoutWidget.raise_()
        self.label_XrayStatus.raise_()
        self.textEdit_XrayLog.raise_()
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("tab_高压控制器.bmp"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget_2.addTab(self.tab_12, icon4, "")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.horizontalLayoutWidget_7 = QtWidgets.QWidget(self.tab_7)
        self.horizontalLayoutWidget_7.setGeometry(QtCore.QRect(300, 370, 361, 31))
        self.horizontalLayoutWidget_7.setObjectName("horizontalLayoutWidget_7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout_7.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.pushButton_12 = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_7.addWidget(self.pushButton_12)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem14)
        self.pushButton_13 = QtWidgets.QPushButton(self.horizontalLayoutWidget_7)
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_7.addWidget(self.pushButton_13)
        self.label_15 = QtWidgets.QLabel(self.tab_7)
        self.label_15.setGeometry(QtCore.QRect(300, 30, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.textEdit_5 = QtWidgets.QTextEdit(self.tab_7)
        self.textEdit_5.setGeometry(QtCore.QRect(300, 60, 361, 301))
        self.textEdit_5.setObjectName("textEdit_5")
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.tab_5)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(50, 20, 551, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem15)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.textEdit_AutoLog = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit_AutoLog.setGeometry(QtCore.QRect(50, 60, 321, 331))
        self.textEdit_AutoLog.setObjectName("textEdit_AutoLog")
        self.textEdit_ManualLog = QtWidgets.QTextEdit(self.tab_5)
        self.textEdit_ManualLog.setGeometry(QtCore.QRect(540, 60, 321, 301))
        self.textEdit_ManualLog.setObjectName("textEdit_ManualLog")
        self.btn_AddLog = QtWidgets.QPushButton(self.tab_5)
        self.btn_AddLog.setGeometry(QtCore.QRect(540, 370, 321, 23))
        self.btn_AddLog.setObjectName("btn_AddLog")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.textEdit_Doc = QtWidgets.QTextEdit(self.tab_6)
        self.textEdit_Doc.setGeometry(QtCore.QRect(70, 30, 801, 401))
        self.textEdit_Doc.setObjectName("textEdit_Doc")
        self.tabWidget.addTab(self.tab_6, "")
        self.btn_Quit = QtWidgets.QPushButton(self.centralWidget)
        self.btn_Quit.setGeometry(QtCore.QRect(830, 490, 75, 23))
        self.btn_Quit.setCheckable(False)
        self.btn_Quit.setObjectName("btn_Quit")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 991, 23))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        self.tabWidget_3.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_13.setText(_translate("MainWindow", "用户名："))
        self.lineEdit_UserName.setText(_translate("MainWindow", "CT"))
        self.label_14.setText(_translate("MainWindow", "密码："))
        self.lineEdit_PassWord.setText(_translate("MainWindow", "nsrl"))
        self.btn_Login.setText(_translate("MainWindow", "登录"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "用户管理"))
        self.label_11.setText(_translate("MainWindow", "扫描模式："))
        self.comboBox_ScanMode.setItemText(0, _translate("MainWindow", "传统相位步进"))
        self.comboBox_ScanMode.setItemText(1, _translate("MainWindow", "周步进"))
        self.comboBox_ScanMode.setItemText(2, _translate("MainWindow", "免步进"))
        self.label_3.setText(_translate("MainWindow", "G1光栅周期P："))
        self.label_8.setText(_translate("MainWindow", "样品视场Y方向长度L：        "))
        self.label_7.setText(_translate("MainWindow", "G1光栅步进数N："))
        self.label_10.setText(_translate("MainWindow", "样品高度H："))
        self.label_9.setText(_translate("MainWindow", "每圈采集次数K："))
        self.btn_WriteParameter.setText(_translate("MainWindow", "写入以上参数"))
        self.btn_ScanStart.setText(_translate("MainWindow", "开始扫描"))
        self.btn_ScanStop.setText(_translate("MainWindow", "停止扫描"))
        self.label_4.setText(_translate("MainWindow", "传感器状态"))
        self.pushButton_4.setText(_translate("MainWindow", "暗电流校正"))
        self.pushButton_3.setText(_translate("MainWindow", "归一化校正"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "扫描控制"))
        self.label_5.setText(_translate("MainWindow", "图片显示"))
        self.label_6.setText(_translate("MainWindow", "图片信息"))
        self.pushButton_5.setText(_translate("MainWindow", "选取图片"))
        self.pushButton_6.setText(_translate("MainWindow", "修改参数"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "影像显示"))
        self.groupBox_3.setTitle(_translate("MainWindow", "选择参数"))
        self.groupBox_4.setTitle(_translate("MainWindow", "输入位置"))
        self.groupBox_5.setTitle(_translate("MainWindow", "操作按钮"))
        self.label_21.setText(_translate("MainWindow", "位移台序号"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "G0光栅"))
        self.label_22.setText(_translate("MainWindow", "位移台类型"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "平移"))
        self.label_23.setText(_translate("MainWindow", "轴名称"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "Z轴"))
        self.label_24.setText(_translate("MainWindow", "运动模式"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "相对运动"))
        self.label_25.setText(_translate("MainWindow", "运动速度"))
        self.comboBox_7.setItemText(0, _translate("MainWindow", "中速"))
        self.lineEdit_12.setText(_translate("MainWindow", "12.55"))
        self.label_27.setText(_translate("MainWindow", "位移台当前位置"))
        self.label_26.setText(_translate("MainWindow", "输入运动位置"))
        self.label_28.setText(_translate("MainWindow", "mm"))
        self.label_29.setText(_translate("MainWindow", "mm"))
        self.pushButton_20.setText(_translate("MainWindow", "初始化"))
        self.pushButton_2.setText(_translate("MainWindow", "移动"))
        self.pushButton_18.setText(_translate("MainWindow", "停止"))
        self.pushButton_19.setText(_translate("MainWindow", "关闭当前电机"))
        self.pushButton_21.setText(_translate("MainWindow", "关闭所有电机"))
        self.pushButton_22.setText(_translate("MainWindow", "保存运动参数"))
        self.groupBox_6.setTitle(_translate("MainWindow", "执行操作"))
        self.btn_SampleOff.setText(_translate("MainWindow", "关闭电机"))
        self.btn_SampleStop.setText(_translate("MainWindow", "停止运动"))
        self.btn_SampleOriginStart.setText(_translate("MainWindow", "回原点启动"))
        self.btn_SampleOn.setText(_translate("MainWindow", "打开电机"))
        self.btn_SampleDirectionStart.setText(_translate("MainWindow", "正反转启动"))
        self.groupBox_7.setTitle(_translate("MainWindow", "选择参数"))
        self.label_32.setText(_translate("MainWindow", "运行模式"))
        self.label_31.setText(_translate("MainWindow", "mm/s"))
        self.label_33.setText(_translate("MainWindow", "目标位置"))
        self.label_30.setText(_translate("MainWindow", "运动速度"))
        self.comboBox_SampleMode.setItemText(0, _translate("MainWindow", "点动模式"))
        self.comboBox_SampleMode.setItemText(1, _translate("MainWindow", "定位运动模式"))
        self.comboBox_SampleDirection.setItemText(0, _translate("MainWindow", "正向"))
        self.comboBox_SampleDirection.setItemText(1, _translate("MainWindow", "反向"))
        self.label_35.setText(_translate("MainWindow", "运动方向"))
        self.lineEdit_SampleDestPosition.setText(_translate("MainWindow", "0"))
        self.lineEdit_SampleSpeed.setText(_translate("MainWindow", "0"))
        self.label_34.setText(_translate("MainWindow", "mm"))
        self.groupBox_8.setTitle(_translate("MainWindow", "选择电机"))
        self.comboBox_SampleSelect.setItemText(0, _translate("MainWindow", "升降电机"))
        self.comboBox_SampleSelect.setItemText(1, _translate("MainWindow", "旋转电机"))
        self.btn_XrayStart.setText(_translate("MainWindow", "Start"))
        self.lineEdit_XrayKv.setText(_translate("MainWindow", "80"))
        self.label_16.setText(_translate("MainWindow", "kV"))
        self.btn_XrayExpose.setText(_translate("MainWindow", "Expose"))
        self.label_19.setText(_translate("MainWindow", "Focal"))
        self.btn_XrayStop.setText(_translate("MainWindow", "Stop"))
        self.lineEdit_XrayMa.setText(_translate("MainWindow", "50"))
        self.lineEdit_XrayTime.setText(_translate("MainWindow", "3"))
        self.btn_XrayPrepare.setText(_translate("MainWindow", "Prepare"))
        self.label_18.setText(_translate("MainWindow", "Time"))
        self.label_17.setText(_translate("MainWindow", "mA"))
        self.comboBox_XrayFcoal.setItemText(0, _translate("MainWindow", "Large"))
        self.comboBox_XrayFcoal.setItemText(1, _translate("MainWindow", "Small"))
        self.label_XrayStatus.setText(_translate("MainWindow", "Status"))
        self.textEdit_XrayLog.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Start成功</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">等待参数设置...</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Prepare参数设置成功</p></body></html>"))
        self.groupBox.setTitle(_translate("MainWindow", "曝光设置"))
        self.groupBox_2.setTitle(_translate("MainWindow", "返回信息"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "设备维护"))
        self.pushButton_12.setText(_translate("MainWindow", "刷新"))
        self.pushButton_13.setText(_translate("MainWindow", "急停"))
        self.label_15.setText(_translate("MainWindow", "联锁状态"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("MainWindow", "安全联锁"))
        self.label_2.setText(_translate("MainWindow", "日志显示"))
        self.label.setText(_translate("MainWindow", "添加日志"))
        self.btn_AddLog.setText(_translate("MainWindow", "添加日志"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "操作日志"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "帮助文档"))
        self.btn_Quit.setText(_translate("MainWindow", "退出系统"))

